use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct SourceEndpointCatalogEntry {
    pub provider: &'static str,
    pub endpoint_key: &'static str,
    pub method: &'static str,
    pub path_template: &'static str,
    pub transport: &'static str,
    pub category: &'static str,
    pub ingest_strategy: &'static str,
    pub source_of_truth: &'static str,
    pub notes: &'static str,
}

const OWLS_DOC: &str = "https://owlsinsight.com/docs#coverage";
const ODDS_API_DOC: &str = "https://the-odds-api.com/liveapi/guides/v4/";
const ODDSENTRY_DOC: &str = "reverse-engineered:/home/user/projects/sabi/data/oddsentry-live-probe-2026-04-03/report-deep.md";
const FAIRODDS_DOC: &str =
    "reverse-engineered:/home/user/projects/sabi/data/fairodds-pro-auth-scrape-2026-03-09.json";

pub fn all_endpoint_catalog_entries() -> Vec<SourceEndpointCatalogEntry> {
    let mut entries = Vec::new();
    entries.extend(owls_entries());
    entries.extend(odds_api_entries());
    entries.extend(oddsentry_entries());
    entries.extend(fairodds_entries());
    entries
}

fn owls_entries() -> Vec<SourceEndpointCatalogEntry> {
    vec![
        entry(
            "owls",
            "sport_odds",
            "GET",
            "/api/v1/{sport}/odds",
            "rest",
            "odds",
            "on_demand_sport",
            OWLS_DOC,
            "Primary all-books odds feed by sport.",
        ),
        entry(
            "owls",
            "sport_moneyline",
            "GET",
            "/api/v1/{sport}/moneyline",
            "rest",
            "odds",
            "on_demand_sport",
            OWLS_DOC,
            "Moneyline-only variant.",
        ),
        entry(
            "owls",
            "sport_spreads",
            "GET",
            "/api/v1/{sport}/spreads",
            "rest",
            "odds",
            "on_demand_sport",
            OWLS_DOC,
            "Spread-only variant.",
        ),
        entry(
            "owls",
            "sport_totals",
            "GET",
            "/api/v1/{sport}/totals",
            "rest",
            "odds",
            "on_demand_sport",
            OWLS_DOC,
            "Totals-only variant.",
        ),
        entry(
            "owls",
            "sport_props",
            "GET",
            "/api/v1/{sport}/props",
            "rest",
            "props",
            "on_demand_sport",
            OWLS_DOC,
            "Aggregated player props.",
        ),
        entry(
            "owls",
            "cs2_odds",
            "GET",
            "/api/v1/cs2/odds",
            "rest",
            "odds",
            "on_demand_sport",
            OWLS_DOC,
            "Explicit esport odds route.",
        ),
        entry(
            "owls",
            "valorant_odds",
            "GET",
            "/api/v1/valorant/odds",
            "rest",
            "odds",
            "on_demand_sport",
            OWLS_DOC,
            "Explicit esport odds route.",
        ),
        entry(
            "owls",
            "lol_odds",
            "GET",
            "/api/v1/lol/odds",
            "rest",
            "odds",
            "on_demand_sport",
            OWLS_DOC,
            "Explicit esport odds route.",
        ),
        entry(
            "owls",
            "sport_splits",
            "GET",
            "/api/v1/{sport}/splits",
            "rest",
            "splits",
            "on_demand_sport",
            OWLS_DOC,
            "Sharp/public split data.",
        ),
        entry(
            "owls",
            "normalize",
            "GET",
            "/api/v1/normalize",
            "rest",
            "utility",
            "on_demand",
            OWLS_DOC,
            "Team-name normalization utility.",
        ),
        entry(
            "owls",
            "scores_live",
            "GET",
            "/api/v1/scores/live",
            "rest",
            "scores",
            "on_demand_sport",
            OWLS_DOC,
            "Live scores across sports.",
        ),
        entry(
            "owls",
            "nba_stats",
            "GET",
            "/api/v1/nba/stats",
            "rest",
            "stats",
            "on_demand_sport",
            OWLS_DOC,
            "NBA box scores.",
        ),
        entry(
            "owls",
            "nba_stats_averages",
            "GET",
            "/api/v1/nba/stats/averages",
            "rest",
            "stats",
            "on_demand_sport",
            OWLS_DOC,
            "NBA rolling averages.",
        ),
        entry(
            "owls",
            "history_games",
            "GET",
            "/api/v1/history/games",
            "rest",
            "history",
            "on_demand_history",
            OWLS_DOC,
            "Archived game list.",
        ),
        entry(
            "owls",
            "history_odds",
            "GET",
            "/api/v1/history/odds",
            "rest",
            "history",
            "on_demand_history",
            OWLS_DOC,
            "Historical odds snapshots.",
        ),
        entry(
            "owls",
            "history_props",
            "GET",
            "/api/v1/history/props",
            "rest",
            "history",
            "on_demand_history",
            OWLS_DOC,
            "Historical props snapshots.",
        ),
        entry(
            "owls",
            "history_stats",
            "GET",
            "/api/v1/history/stats",
            "rest",
            "history",
            "on_demand_history",
            OWLS_DOC,
            "Historical player box scores.",
        ),
        entry(
            "owls",
            "props_book_stats",
            "GET",
            "/api/v1/props/{book}/stats",
            "rest",
            "props",
            "on_demand_book",
            OWLS_DOC,
            "Per-book prop cache statistics.",
        ),
        entry(
            "owls",
            "history_public_betting",
            "GET",
            "/api/v1/history/public-betting",
            "rest",
            "history",
            "on_demand_history",
            OWLS_DOC,
            "Historical public betting percentages.",
        ),
        entry(
            "owls",
            "realtime",
            "GET",
            "/api/v1/{sport}/realtime",
            "rest",
            "realtime",
            "stream_or_poll",
            OWLS_DOC,
            "Real-time sharp odds.",
        ),
        entry(
            "owls",
            "realtime_ps3838",
            "GET",
            "/api/v1/{sport}/ps3838-realtime",
            "rest",
            "realtime",
            "stream_or_poll",
            OWLS_DOC,
            "Backup PS3838/Pinnacle-style realtime feed.",
        ),
        entry(
            "owls",
            "websocket",
            "WS",
            "https://api.owlsinsight.com",
            "websocket",
            "stream",
            "stream_subscription",
            OWLS_DOC,
            "Documented channels include odds-update, player-props-update, esports-update, pinnacle-realtime, ps3838-realtime.",
        ),
    ]
}

fn odds_api_entries() -> Vec<SourceEndpointCatalogEntry> {
    vec![
        entry(
            "oddsapi",
            "sports",
            "GET",
            "/v4/sports?apiKey={apiKey}",
            "rest",
            "sports",
            "auto_refresh_registry",
            ODDS_API_DOC,
            "Registry of in-season sports.",
        ),
        entry(
            "oddsapi",
            "sport_odds",
            "GET",
            "/v4/sports/{sport}/odds?apiKey={apiKey}&regions={regions}&markets={markets}",
            "rest",
            "odds",
            "auto_refresh_sport",
            ODDS_API_DOC,
            "Upcoming/live featured market odds for a sport.",
        ),
        entry(
            "oddsapi",
            "sport_scores",
            "GET",
            "/v4/sports/{sport}/scores?apiKey={apiKey}&daysFrom={daysFrom}&dateFormat={dateFormat}",
            "rest",
            "scores",
            "auto_refresh_sport",
            ODDS_API_DOC,
            "Upcoming/live/recently-completed scores for a sport.",
        ),
        entry(
            "oddsapi",
            "sport_events",
            "GET",
            "/v4/sports/{sport}/events?apiKey={apiKey}",
            "rest",
            "events",
            "auto_refresh_sport",
            ODDS_API_DOC,
            "Current event IDs for a sport.",
        ),
        entry(
            "oddsapi",
            "event_odds",
            "GET",
            "/v4/sports/{sport}/events/{eventId}/odds?apiKey={apiKey}&regions={regions}&markets={markets}&dateFormat={dateFormat}&oddsFormat={oddsFormat}",
            "rest",
            "event_odds",
            "on_demand_event",
            ODDS_API_DOC,
            "Required for non-featured markets such as player props and alternate markets.",
        ),
        entry(
            "oddsapi",
            "historical_sport_odds",
            "GET",
            "/v4/historical/sports/{sport}/odds?apiKey={apiKey}&regions={regions}&markets={markets}&date={date}",
            "rest",
            "history",
            "on_demand_history",
            ODDS_API_DOC,
            "Historical featured-market odds snapshots by sport.",
        ),
        entry(
            "oddsapi",
            "historical_sport_events",
            "GET",
            "/v4/historical/sports/{sport}/events?apiKey={apiKey}&date={date}",
            "rest",
            "history",
            "on_demand_history",
            ODDS_API_DOC,
            "Historical event IDs at a timestamp.",
        ),
        entry(
            "oddsapi",
            "historical_event_odds",
            "GET",
            "/v4/historical/sports/{sport}/events/{eventId}/odds?apiKey={apiKey}&regions={regions}&markets={markets}&dateFormat={dateFormat}&oddsFormat={oddsFormat}&date={date}",
            "rest",
            "history",
            "on_demand_history_event",
            ODDS_API_DOC,
            "Historical event-specific odds, including additional markets after 2023-05-03T05:30:00Z.",
        ),
    ]
}

fn oddsentry_entries() -> Vec<SourceEndpointCatalogEntry> {
    vec![
        entry(
            "oddsentry",
            "bookmakers",
            "GET",
            "/v1/bookmakers",
            "rest",
            "registry",
            "auto_refresh_registry",
            ODDSENTRY_DOC,
            "Observed bookmaker registry.",
        ),
        entry(
            "oddsentry",
            "games",
            "GET",
            "/v1/games",
            "rest",
            "registry",
            "auto_refresh_registry",
            ODDSENTRY_DOC,
            "Observed game/sport registry.",
        ),
        entry(
            "oddsentry",
            "odds",
            "GET",
            "/v1/odds",
            "rest",
            "odds",
            "auto_refresh_primary",
            ODDSENTRY_DOC,
            "Primary match summary feed.",
        ),
        entry(
            "oddsentry",
            "odds_filtered",
            "GET",
            "/v1/odds?bookmakers={bookmakers}",
            "rest",
            "odds",
            "on_demand_query",
            ODDSENTRY_DOC,
            "Filtered odds feed by bookmakers.",
        ),
        entry(
            "oddsentry",
            "event_detail",
            "GET",
            "/v1/odds/{eventId}",
            "rest",
            "event_detail",
            "on_demand_event",
            ODDSENTRY_DOC,
            "Detailed event odds board.",
        ),
        entry(
            "oddsentry",
            "historical_raw",
            "GET",
            "/v1/odds/{eventId}/historical?resolution=raw",
            "rest",
            "history",
            "on_demand_history_event",
            ODDSENTRY_DOC,
            "Raw historical odds series.",
        ),
        entry(
            "oddsentry",
            "historical_hourly",
            "GET",
            "/v1/odds/{eventId}/historical?resolution=hourly",
            "rest",
            "history",
            "on_demand_history_event",
            ODDSENTRY_DOC,
            "Hourly historical odds fallback.",
        ),
        entry(
            "oddsentry",
            "live_event",
            "GET",
            "/v1/odds/{eventId}/live",
            "rest",
            "live",
            "on_demand_event",
            ODDSENTRY_DOC,
            "Live-only event feed used by graph UI.",
        ),
        entry(
            "oddsentry",
            "arbitrages",
            "GET",
            "/v1/arbitrages",
            "rest",
            "arbitrage",
            "auto_refresh_primary",
            ODDSENTRY_DOC,
            "Arbitrage opportunities feed.",
        ),
        entry(
            "oddsentry",
            "positive_ev",
            "GET",
            "/v1/positive_ev",
            "rest",
            "positive_ev",
            "auto_refresh_primary",
            ODDSENTRY_DOC,
            "Positive EV opportunities feed.",
        ),
        entry(
            "oddsentry",
            "redirect",
            "GET",
            "/v1/redirect/{id}",
            "rest",
            "utility",
            "on_demand_event",
            ODDSENTRY_DOC,
            "Resolves outbound bookmaker links.",
        ),
        entry(
            "oddsentry",
            "notifications_eligibility",
            "GET",
            "/v1/notifications/eligibility",
            "rest",
            "notifications",
            "auto_refresh_registry",
            ODDSENTRY_DOC,
            "Feature eligibility for notifications.",
        ),
        entry(
            "oddsentry",
            "notifications_list",
            "GET",
            "/v1/notifications",
            "rest",
            "notifications",
            "auto_refresh_user",
            ODDSENTRY_DOC,
            "Current user notification rules.",
        ),
        entry(
            "oddsentry",
            "notifications_create",
            "POST",
            "/v1/notifications",
            "rest",
            "notifications",
            "manual_mutation",
            ODDSENTRY_DOC,
            "Creates notification rules.",
        ),
        entry(
            "oddsentry",
            "notifications_update",
            "POST",
            "/v1/notifications/{id}",
            "rest",
            "notifications",
            "manual_mutation",
            ODDSENTRY_DOC,
            "Updates notification rules.",
        ),
        entry(
            "oddsentry",
            "notifications_delete",
            "DELETE",
            "/v1/notifications/{id}",
            "rest",
            "notifications",
            "manual_mutation",
            ODDSENTRY_DOC,
            "Deletes notification rules.",
        ),
        entry(
            "oddsentry",
            "websocket",
            "WS",
            "wss://api.oddsentry.com/ws",
            "websocket",
            "stream",
            "stream_subscription",
            ODDSENTRY_DOC,
            "Observed websocket transport from live terminal capture.",
        ),
    ]
}

fn fairodds_entries() -> Vec<SourceEndpointCatalogEntry> {
    vec![
        entry(
            "fair_odds",
            "value_calculated",
            "GET",
            "/api/value-calculated",
            "rest",
            "value",
            "fixture_or_auth_refresh",
            FAIRODDS_DOC,
            "Primary EV/value feed with parameterized filters and joined drop enrichment.",
        ),
        entry(
            "fair_odds",
            "droppers",
            "GET",
            "/droppers?windowSec={windowSec}&sort=time&timing={timing}",
            "rest",
            "droppers",
            "fixture_or_auth_refresh",
            FAIRODDS_DOC,
            "Observed live drop feed.",
        ),
        entry(
            "fair_odds",
            "pinn_events",
            "GET",
            "/api/pinn-events",
            "rest",
            "registry",
            "on_demand_registry",
            FAIRODDS_DOC,
            "Event listing used by droppers flow.",
        ),
        entry(
            "fair_odds",
            "bg_stream",
            "GET",
            "/bg/stream",
            "sse",
            "stream",
            "stream_subscription",
            FAIRODDS_DOC,
            "Server-sent event trigger used to re-fetch value-calculated.",
        ),
        entry(
            "fair_odds",
            "sports_details",
            "GET",
            "/api/sports/details",
            "rest",
            "registry",
            "on_demand_registry",
            FAIRODDS_DOC,
            "Sport metadata used by bets widget.",
        ),
        entry(
            "fair_odds",
            "books_allowed",
            "GET",
            "/api/books-allowed",
            "rest",
            "registry",
            "on_demand_registry",
            FAIRODDS_DOC,
            "Exchange/sharp book allowlist.",
        ),
        entry(
            "fair_odds",
            "clv_compute",
            "POST",
            "/api/clv/compute",
            "rest",
            "bets",
            "manual_mutation",
            FAIRODDS_DOC,
            "CLV recomputation for tracked bets.",
        ),
        entry(
            "fair_odds",
            "chat_ws",
            "WS",
            "/chat/ws",
            "websocket",
            "chat",
            "stream_subscription",
            FAIRODDS_DOC,
            "Public chat websocket.",
        ),
        entry(
            "fair_odds",
            "chat_list",
            "GET",
            "/chat",
            "rest",
            "chat",
            "manual_query",
            FAIRODDS_DOC,
            "Chat fetch endpoint.",
        ),
        entry(
            "fair_odds",
            "chat_delete",
            "POST",
            "/chat/delete",
            "rest",
            "chat",
            "manual_mutation",
            FAIRODDS_DOC,
            "Chat delete endpoint.",
        ),
        entry(
            "fair_odds",
            "dm_conversations",
            "GET",
            "/dm/conversations",
            "rest",
            "dm",
            "manual_query",
            FAIRODDS_DOC,
            "DM conversation list.",
        ),
        entry(
            "fair_odds",
            "dm_messages",
            "GET",
            "/dm/messages/{id}",
            "rest",
            "dm",
            "manual_query",
            FAIRODDS_DOC,
            "DM message history.",
        ),
        entry(
            "fair_odds",
            "dm_user_search",
            "GET",
            "/dm/users/search?q={query}",
            "rest",
            "dm",
            "manual_query",
            FAIRODDS_DOC,
            "DM user search.",
        ),
        entry(
            "fair_odds",
            "dm_start",
            "POST",
            "/dm/start",
            "rest",
            "dm",
            "manual_mutation",
            FAIRODDS_DOC,
            "Start DM conversation.",
        ),
        entry(
            "fair_odds",
            "dm_send",
            "POST",
            "/dm/send",
            "rest",
            "dm",
            "manual_mutation",
            FAIRODDS_DOC,
            "Send DM message.",
        ),
        entry(
            "fair_odds",
            "auth_user",
            "GET",
            "https://auth.fairoddsterminal.com/auth/v1/user",
            "rest",
            "auth",
            "manual_query",
            FAIRODDS_DOC,
            "Supabase auth user lookup.",
        ),
        entry(
            "fair_odds",
            "rest_books",
            "GET",
            "https://auth.fairoddsterminal.com/rest/v1/books?select=id,name",
            "rest",
            "bets",
            "manual_query",
            FAIRODDS_DOC,
            "Books registry backing bets widget.",
        ),
        entry(
            "fair_odds",
            "rest_bets",
            "GET",
            "https://auth.fairoddsterminal.com/rest/v1/bets?...",
            "rest",
            "bets",
            "manual_query",
            FAIRODDS_DOC,
            "Tracked bets listing from Supabase.",
        ),
        entry(
            "fair_odds",
            "rest_bets_update",
            "PATCH",
            "https://auth.fairoddsterminal.com/rest/v1/bets",
            "rest",
            "bets",
            "manual_mutation",
            FAIRODDS_DOC,
            "Supabase update path inferred from bets widget.",
        ),
        entry(
            "fair_odds",
            "rest_bets_delete",
            "DELETE",
            "https://auth.fairoddsterminal.com/rest/v1/bets",
            "rest",
            "bets",
            "manual_mutation",
            FAIRODDS_DOC,
            "Supabase delete path inferred from bets widget.",
        ),
        entry(
            "fair_odds",
            "rest_user_settings_filters",
            "GET",
            "https://auth.fairoddsterminal.com/rest/v1/user_settings_filters",
            "rest",
            "settings",
            "manual_query",
            FAIRODDS_DOC,
            "Watchlist/filter persistence.",
        ),
        entry(
            "fair_odds",
            "rpc_leaderboard_last_month",
            "POST",
            "https://auth.fairoddsterminal.com/rest/v1/rpc/leaderboard_last_month",
            "rest",
            "analytics",
            "manual_query",
            FAIRODDS_DOC,
            "Leaderboard analytics RPC.",
        ),
    ]
}

fn entry(
    provider: &'static str,
    endpoint_key: &'static str,
    method: &'static str,
    path_template: &'static str,
    transport: &'static str,
    category: &'static str,
    ingest_strategy: &'static str,
    source_of_truth: &'static str,
    notes: &'static str,
) -> SourceEndpointCatalogEntry {
    SourceEndpointCatalogEntry {
        provider,
        endpoint_key,
        method,
        path_template,
        transport,
        category,
        ingest_strategy,
        source_of_truth,
        notes,
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::all_endpoint_catalog_entries;

    #[test]
    fn endpoint_catalog_has_unique_provider_keys() {
        let entries = all_endpoint_catalog_entries();
        let mut ids = HashSet::new();
        for entry in entries {
            assert!(ids.insert((entry.provider, entry.endpoint_key)));
        }
    }
}
